### ISSUE TITLE
Problem to use with eclipse

### ISSUE THREAD

**Issue by colesnicov** [sleemanj/optiboot#10]
Hello. Trying to use your core with the eclipse + arduino plugin. I try to program attiny13a. I get this error:

Failed to find diy_attiny:avrdude_nobootloader_noefuse reference in /home/denis/opt/eclipse/arduinoPlugin/packages/diy_attiny/hardware/avr/2018.3.11/boards.txt for attiny13_diy:

**Comment by sleemanj** [comment]
Eclipse is not supported sorry
