### ISSUE TITLE
Error downloading https://raw.githubusercontent.com/sleemanj/optiboot/master/dists/package_gogo_diy_attiny_index.json

### ISSUE THREAD

**Issue by ignitionelectronics** [sleemanj/optiboot#16]
Error downloading https://raw.githubusercontent.com/sleemanj/optiboot/master/dists/package_gogo_diy_attiny_index.json

This is show in arduino ide what i do ??

**Comment by sleemanj** [comment]
It downloads fine for me.  Probably a network problem at your end.  Click the link in your browser and see if you can view it there.  Try again maybe.

**Comment by ignitionelectronics** [comment]
Thank you so much for helping Yes I  am able to solve it this is because of network problem.
