### ISSUE TITLE
Cannot compile example

### ISSUE THREAD

**Issue by mrohner** [sleemanj/optiboot#2]
Hi,
I'm using newest IDE and cannot get the sample program to compile. Any help appreciated. Just wanted to see how much memory this program uses.

`Arduino: 1.8.4 (Windows 10), Board: "ATtiny13, ATtiny13a, No (ISP Programmer Upload), 9.6MHz Internal Oscillator, Millis Available, No Tone, Better Or Equal 1.666% Error (Default), Bin Only Supported (Smallest), Half Duplex, Write Only Inherits Stream, LTO Enabled, 1.8v"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\marku\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\marku\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\marku\Documents\Arduino\libraries -fqbn=diy_attiny:avr:attiny13_diy:version=attiny13a,boot=none,clock=9_6MHz,core=MillisCore,millis_ppm=1p6,print=Bin,serial=HalfDuplexWStream,lto=enable,bodlevel=1v8 -ide-version=10804 -build-path C:\Users\marku\AppData\Local\Temp\arduino_build_453020 -warnings=all -build-cache C:\Users\marku\AppData\Local\Temp\arduino_cache_689587 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino6 -prefs=runtime.tools.avr-gcc.path=C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2 -verbose C:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\libraries\ATTinyCore\examples\Tiny13\02.Digital\BlinkWithoutDelay\BlinkWithoutDelay.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\marku\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\marku\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\marku\Documents\Arduino\libraries -fqbn=diy_attiny:avr:attiny13_diy:version=attiny13a,boot=none,clock=9_6MHz,core=MillisCore,millis_ppm=1p6,print=Bin,serial=HalfDuplexWStream,lto=enable,bodlevel=1v8 -ide-version=10804 -build-path C:\Users\marku\AppData\Local\Temp\arduino_build_453020 -warnings=all -build-cache C:\Users\marku\AppData\Local\Temp\arduino_cache_689587 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino6 -prefs=runtime.tools.avr-gcc.path=C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2 -verbose C:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\libraries\ATTinyCore\examples\Tiny13\02.Digital\BlinkWithoutDelay\BlinkWithoutDelay.ino
Using board 'attiny13_diy' from platform in folder: C:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8
Using core 'tiny' from platform in folder: C:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8
Detecting libraries used...
"C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -DLTO_ENABLED -w -x c++ -E -CC -mmcu=attiny13 -DF_CPU=9600000L -DARDUINO=10804 -DARDUINO_ATTINY13_DIY -DARDUINO_ARCH_AVR  -DNO_TONE -DUSE_SERIAL_TYPE=SERIAL_TYPE_HALF_DUPLEX -DHALF_DUPLEX_SERIAL_DISABLE_READ -DPRINT_USE_BASE_BIN -DACCEPTABLE_MILLIS_ERROR_PPM=16666UL "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\cores\tiny" "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\variants\tiny13" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\sketch\BlinkWithoutDelay.ino.cpp" -o "nul"
Generating function prototypes...
"C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -DLTO_ENABLED -w -x c++ -E -CC -mmcu=attiny13 -DF_CPU=9600000L -DARDUINO=10804 -DARDUINO_ATTINY13_DIY -DARDUINO_ARCH_AVR  -DNO_TONE -DUSE_SERIAL_TYPE=SERIAL_TYPE_HALF_DUPLEX -DHALF_DUPLEX_SERIAL_DISABLE_READ -DPRINT_USE_BASE_BIN -DACCEPTABLE_MILLIS_ERROR_PPM=16666UL "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\cores\tiny" "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\variants\tiny13" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\sketch\BlinkWithoutDelay.ino.cpp" -o "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -DLTO_ENABLED -mmcu=attiny13 -DF_CPU=9600000L -DARDUINO=10804 -DARDUINO_ATTINY13_DIY -DARDUINO_ARCH_AVR  -DNO_TONE -DUSE_SERIAL_TYPE=SERIAL_TYPE_HALF_DUPLEX -DHALF_DUPLEX_SERIAL_DISABLE_READ -DPRINT_USE_BASE_BIN -DACCEPTABLE_MILLIS_ERROR_PPM=16666UL "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\cores\tiny" "-IC:\Users\marku\AppData\Local\Arduino15\packages\diy_attiny\hardware\avr\2017.6.8\variants\tiny13" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\sketch\BlinkWithoutDelay.ino.cpp" -o "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\sketch\BlinkWithoutDelay.ino.cpp.o"
Compiling libraries...
Compiling core...
Using previously compiled file: C:\Users\marku\AppData\Local\Temp\arduino_build_453020\core\pins_arduino.c.o
Using previously compiled file: C:\Users\marku\AppData\Local\Temp\arduino_build_453020\core\Tone.cpp.o
Using precompiled core
Linking everything together...
"C:\Users\marku\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.3-arduino2/bin/avr-gcc" -Wall -Wextra -Os -g -flto -DLTO_ENABLED -fuse-linker-plugin -Wl,--gc-sections -mmcu=attiny13  -o "C:\Users\marku\AppData\Local\Temp\arduino_build_453020/BlinkWithoutDelay.ino.elf" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\sketch\BlinkWithoutDelay.ino.cpp.o" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\core\pins_arduino.c.o" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020\core\Tone.cpp.o" "C:\Users\marku\AppData\Local\Temp\arduino_build_453020/..\arduino_cache_689587\core\core_diy_attiny_avr_attiny13_diy_version_attiny13a,boot_none,clock_9_6MHz,core_MillisCore,millis_ppm_1p6,print_Bin,serial_HalfDuplexWStream,lto_enable,bodlevel_1v8_ffb33527d64033fb492cc2c1068e918e.a" "-LC:\Users\marku\AppData\Local\Temp\arduino_build_453020" -lm
avr-gcc: error: C:\Users\marku\AppData\Local\Temp\arduino_build_453020/..\arduino_cache_689587\core\core_diy_attiny_avr_attiny13_diy_version_attiny13a,boot_none,clock_9_6MHz,core_MillisCore,millis_ppm_1p6,print_Bin,serial_HalfDuplexWStream,lto_enable,bodlevel_1v8_ffb33527d64033fb492cc2c1068e918e.a: No such file or directory

exit status 1
Error compiling for board ATtiny13.`

**Comment by sleemanj** [comment]
Sorry I didn't see this ticket at the time.  

I'm unable to reproduce this in 1.8.5 on my Linux box (up to now I have been using 1.6.13), if you are still experiencing this in 1.8.5 on your Windows box let me know.

I see that the Arduino build process has changed sometime and it uses archived cores (the crazy "ore_diy_attiny_avr_attiny13_diy_version_attiny13a,boot_none,clock_9_6MHz,core_MillisCore,millis_ppm_1p6,print_Bin,serial_HalfDuplexWStream,lto_enable,bodlevel_1v8_ffb33527d64033fb492cc2c1068e918e.a:" it is trying to find in your error), perhaps they had some bug there.
