### ISSUE TITLE
digitalPinToInterrupt(PIN_X) does not work

### ISSUE THREAD

**Issue by skaman82** [sleemanj/optiboot#22]
Code:  
attachInterrupt( digitalPinToInterrupt(2) , isr, CHANGE ) ;

Compiler Error:
'sketch/IrNec.cpp: In function 'void nsIrNec::begin(uint8_t)':
IrNec.cpp:115:43: error: 'digitalPinToInterrupt' was not declared in this scope
   attachInterrupt( digitalPinToInterrupt(2) , isr, CHANGE ) ;
                                           ^
exit status 1
'digitalPinToInterrupt' was not declared in this scope'

Compiling for ATtiny85

**Comment by sleemanj** [comment]
Timy 85 only has one external interrupt, just use it directly.



attachInterrupt( 0, isr, CHANGE ) ;





---- On Thu, 21 Jan 2021 23:38:44 +1300 Albert Kravcov <notifications@github.com> wrote ----




Code:
 attachInterrupt( digitalPinToInterrupt(2) , isr, CHANGE ) ;
Compiler Error:
 'sketch/IrNec.cpp: In function 'void nsIrNec::begin(uint8_t)':
 IrNec.cpp:115:43: error: 'digitalPinToInterrupt' was not declared in this scope
 attachInterrupt( digitalPinToInterrupt(2) , isr, CHANGE ) ;
 ^
 exit status 1
 'digitalPinToInterrupt' was not declared in this scope'
Compiling for ATtiny85

**Comment by skaman82** [comment]
thanks, that helped

**Comment by sleemanj** [comment]
I'll leave this open since I should fix it sometime.

(Specificially I think this is already fixed in the SpenceKonde work pending merging)

**Comment by sleemanj** [comment]
Fixed in 2022.3.10 release
